/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import control.ControlVenta;
import interfaces.IObserver;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.DetalleVenta;
import modelo.Producto;
import modelo.Venta;

/**
 *
 * @author emiim
 */
public class PantallaSeleccion extends javax.swing.JFrame implements IObserver {
    private Venta ventaActual;
    private ControlVenta control;
    
    /**
     * Creates new form PantallaSeleccion
     */
    public PantallaSeleccion(Venta venta) {
        initComponents();
        this.ventaActual = venta;
        this.control = new ControlVenta(venta);
        
        this.ventaActual.agregarObservador(this);
        
        pnlListaProductos.setLayout(new BoxLayout(pnlListaProductos, BoxLayout.Y_AXIS));
        this.setLocationRelativeTo(null);
    }

    public PantallaSeleccion() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelSilla = new javax.swing.JPanel();
        lblSilla = new javax.swing.JLabel();
        btnAgregarSilla = new javax.swing.JButton();
        jPanelTeclado = new javax.swing.JPanel();
        lblTeclado = new javax.swing.JLabel();
        btnAgregarTeclado = new javax.swing.JButton();
        jPanelMouse = new javax.swing.JPanel();
        lblMouse = new javax.swing.JLabel();
        btnAgregarRaton = new javax.swing.JButton();
        jPanelCamara = new javax.swing.JPanel();
        lblCamara = new javax.swing.JLabel();
        btnAgregarCamara = new javax.swing.JButton();
        lblSeleccionProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlCarritoContenedor = new javax.swing.JPanel();
        lblTituloCarrito = new javax.swing.JLabel();
        scpLista = new javax.swing.JScrollPane();
        pnlListaProductos = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal1 = new javax.swing.JLabel();
        lblImpuesto1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFldTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFldVencimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFldCVC = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));

        jPanelSilla.setBackground(new java.awt.Color(255, 255, 255));

        lblSilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/silla.png"))); // NOI18N

        btnAgregarSilla.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarSilla.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarSilla.setText("Agregar");
        btnAgregarSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSillaLayout = new javax.swing.GroupLayout(jPanelSilla);
        jPanelSilla.setLayout(jPanelSillaLayout);
        jPanelSillaLayout.setHorizontalGroup(
            jPanelSillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSillaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSilla)
                .addGap(37, 37, 37))
            .addGroup(jPanelSillaLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnAgregarSilla, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSillaLayout.setVerticalGroup(
            jPanelSillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSillaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSilla)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarSilla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTeclado.setBackground(new java.awt.Color(255, 255, 255));

        lblTeclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teclado.png"))); // NOI18N

        btnAgregarTeclado.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarTeclado.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarTeclado.setText("Agregar");
        btnAgregarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTecladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTecladoLayout = new javax.swing.GroupLayout(jPanelTeclado);
        jPanelTeclado.setLayout(jPanelTecladoLayout);
        jPanelTecladoLayout.setHorizontalGroup(
            jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeclado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTecladoLayout.createSequentialGroup()
                        .addComponent(btnAgregarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanelTecladoLayout.setVerticalGroup(
            jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTeclado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelMouse.setBackground(new java.awt.Color(255, 255, 255));

        lblMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/raton.png"))); // NOI18N

        btnAgregarRaton.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarRaton.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarRaton.setText("Agregar");
        btnAgregarRaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRatonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMouseLayout = new javax.swing.GroupLayout(jPanelMouse);
        jPanelMouse.setLayout(jPanelMouseLayout);
        jPanelMouseLayout.setHorizontalGroup(
            jPanelMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMouseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMouse)
                .addGap(20, 20, 20))
            .addGroup(jPanelMouseLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnAgregarRaton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMouseLayout.setVerticalGroup(
            jPanelMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMouseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarRaton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCamara.setBackground(new java.awt.Color(255, 255, 255));

        lblCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camara.png"))); // NOI18N

        btnAgregarCamara.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarCamara.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarCamara.setText("Agregar");
        btnAgregarCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCamaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCamaraLayout = new javax.swing.GroupLayout(jPanelCamara);
        jPanelCamara.setLayout(jPanelCamaraLayout);
        jPanelCamaraLayout.setHorizontalGroup(
            jPanelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamaraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCamaraLayout.createSequentialGroup()
                        .addComponent(lblCamara)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCamaraLayout.createSequentialGroup()
                        .addComponent(btnAgregarCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanelCamaraLayout.setVerticalGroup(
            jPanelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamaraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCamara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblSeleccionProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSeleccionProductos.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionProductos.setText("Seleccion de Productos");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Elija de nuestra colección premium para su espacio de trabajo.");

        pnlCarritoContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlCarritoContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloCarrito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCarrito.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCarrito.setText("Productos Seleccionados");

        pnlListaProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlListaProductos.setLayout(new javax.swing.BoxLayout(pnlListaProductos, javax.swing.BoxLayout.Y_AXIS));
        scpLista.setViewportView(pnlListaProductos);

        lblSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotal.setText("Subtotal:");

        lblImpuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblImpuesto.setText("Impuesto (8%):");

        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Total Pagado:");

        lblSubtotal1.setForeground(new java.awt.Color(0, 0, 0));

        lblImpuesto1.setForeground(new java.awt.Color(0, 0, 0));

        lblTotal1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlCarritoContenedorLayout = new javax.swing.GroupLayout(pnlCarritoContenedor);
        pnlCarritoContenedor.setLayout(pnlCarritoContenedorLayout);
        pnlCarritoContenedorLayout.setHorizontalGroup(
            pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarritoContenedorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTituloCarrito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarritoContenedorLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCarritoContenedorLayout.createSequentialGroup()
                        .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(lblImpuesto)
                            .addComponent(scpLista, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCarritoContenedorLayout.createSequentialGroup()
                        .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal1)
                            .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblImpuesto1)
                                .addGroup(pnlCarritoContenedorLayout.createSequentialGroup()
                                    .addComponent(lblSubtotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSubtotal1))))
                        .addGap(61, 61, 61))))
        );
        pnlCarritoContenedorLayout.setVerticalGroup(
            pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarritoContenedorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTituloCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpLista, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubtotal1))
                .addGap(18, 18, 18)
                .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuesto)
                    .addComponent(lblImpuesto1))
                .addGap(28, 28, 28)
                .addGroup(pnlCarritoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotal1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ticket de Pago");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRE DEL TITULAR");

        txtFldNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtFldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNombreActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUMERO DE TARJETA");

        txtFldTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        txtFldTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldTarjetaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("VENCIMIENTO");

        txtFldVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtFldVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldVencimientoActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CVC");

        txtFldCVC.setBackground(new java.awt.Color(255, 255, 255));
        txtFldCVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCVCActionPerformed(evt);
            }
        });

        btnPagar.setBackground(new java.awt.Color(0, 153, 255));
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFldVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txtFldCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFldTarjeta, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagar)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFldVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionProductos)
                            .addComponent(jLabel1)))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSilla, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCarritoContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addComponent(lblSeleccionProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(pnlCarritoContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    @Override
    public void actualizar() {
    pnlListaProductos.removeAll();

    for (DetalleVenta d : ventaActual.getDetalles()) {
        
        JPanel fila = new JPanel(new java.awt.BorderLayout());
        fila.setBackground(java.awt.Color.WHITE);
        fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40)); 

        JLabel lblNombre = new JLabel(d.getProducto().getNombre() + " (x" + d.getCantidad() + ")");
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 13));
        fila.add(lblNombre, java.awt.BorderLayout.WEST);

        JButton btnEliminar = new JButton();
        btnEliminar.setText("X");      
        
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEliminar.addActionListener(e -> {
            control.eliminarSeleccion(d); 
        });

        fila.add(btnEliminar, java.awt.BorderLayout.EAST);

        pnlListaProductos.add(fila);
        pnlListaProductos.add(javax.swing.Box.createVerticalStrut(12)); 
    }
    
    lblSubtotal1.setText("$" + String.format("%.2f", ventaActual.getSubtotal()));
    lblImpuesto1.setText("$" + String.format("%.2f", ventaActual.getImpuesto()));
    lblTotal1.setText("$" + String.format("%.2f", ventaActual.getTotal()));
    
    pnlListaProductos.revalidate();
    pnlListaProductos.repaint();
}
    
    private void btnAgregarSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSillaActionPerformed
        Producto p = new Producto("Silla Ergonómica de Oficina", 299.00);
        control.procesarSeleccion(p, 1);
    }//GEN-LAST:event_btnAgregarSillaActionPerformed

    private void btnAgregarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTecladoActionPerformed
        Producto p = new Producto("Teclado Mecánico RGB", 120.00);
        control.procesarSeleccion(p, 1);
    }//GEN-LAST:event_btnAgregarTecladoActionPerformed

    private void btnAgregarRatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRatonActionPerformed
        Producto p = new Producto("Ratón Inalámbrico Ergonómico", 89.99);
        control.procesarSeleccion(p, 1);
    }//GEN-LAST:event_btnAgregarRatonActionPerformed

    private void btnAgregarCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCamaraActionPerformed
        Producto p = new Producto("Cámara Web 4K Pro", 199.00);
        control.procesarSeleccion(p, 1);
    }//GEN-LAST:event_btnAgregarCamaraActionPerformed

    private void txtFldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNombreActionPerformed

    private void txtFldVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldVencimientoActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String tarjeta = txtFldTarjeta.getText(); 
    
    if (control.procesarTransaccion(tarjeta)) {
        PantallaTicket ticket = new PantallaTicket(ventaActual);
        ticket.setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error en la autorización del pago. Tienen que ser maximo 16 caracteres en la tarjeta.");
    }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtFldTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldTarjetaActionPerformed

    private void txtFldCVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCVCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                modelo.Venta ventaInicial = new modelo.Venta("V-001");
                new PantallaSeleccion(ventaInicial).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCamara;
    private javax.swing.JButton btnAgregarRaton;
    private javax.swing.JButton btnAgregarSilla;
    private javax.swing.JButton btnAgregarTeclado;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCamara;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelMouse;
    private javax.swing.JPanel jPanelSilla;
    private javax.swing.JPanel jPanelTeclado;
    private javax.swing.JLabel lblCamara;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblImpuesto1;
    private javax.swing.JLabel lblMouse;
    private javax.swing.JLabel lblSeleccionProductos;
    private javax.swing.JLabel lblSilla;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotal1;
    private javax.swing.JLabel lblTeclado;
    private javax.swing.JLabel lblTituloCarrito;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JPanel pnlCarritoContenedor;
    private javax.swing.JPanel pnlListaProductos;
    private javax.swing.JScrollPane scpLista;
    private javax.swing.JTextField txtFldCVC;
    private javax.swing.JTextField txtFldNombre;
    private javax.swing.JTextField txtFldTarjeta;
    private javax.swing.JTextField txtFldVencimiento;
    // End of variables declaration//GEN-END:variables
}
